### ISSUE TITLE
Points are only given for depicts, which reduces incentive for assessing categories with a lot of "doesn't depict"

### ISSUE THREAD

**Issue by siebrand** [hay/wiki-tools#129]
Points are only given for depicts, which reduces incentive for assessing categories with a lot of "doesn't depict"

Please consider to also award point for selecting "Does not depict". This was observed for example in the challenge "Belgium", where a lot of municipality categories have assets that have depict items in that municipality, but not the municipality itself.

**Comment by hay** [comment]
The leaderboard doesn't indicate points, but number of edits to Commons. Unfortunately there is no way to add a 'this does not depict' statement to Commons. If that would be possible this could probably be added to the leaderboard.
