### ISSUE TITLE
Depictor: show first section of Wikipedia article in the item box

### ISSUE THREAD

**Issue by waldyrious** [hay/wiki-tools#130]
Sometimes it can be unclear whether an image depicts an item without additional information about the scope of the item. The Wikidata label and description aren't always enough to provide confidence about this. For example:

![image](https://github.com/hay/wiki-tools/assets/478237/8408c408-e0a9-4fea-8041-03fc94b613c5)

I would be nice if the box to the left included, under the description, also a snippet from the corresponding Wikipedia article. I believe the [TextExtracts API](https://www.mediawiki.org/wiki/Extension:TextExtracts#API) might be helpful in this regard. In the case above, the content to be fetched would be https://en.wikipedia.org/w/api.php?action=query&prop=extracts&exintro=true&titles=Dandy_horse, which returns the following extract:

`<p>The <b>dandy horse</b>, a derogatory term for what was first called a <b>Laufmaschine</b> (in German), then a <b>v\u00e9locip\u00e8de</b> or <b>draisienne</b> (in French and then English), and then a <b>pedestrian curricle</b> or <b>hobby-horse</b>, or <b>swiftwalker</b>, is a human-powered vehicle that, being the first means of transport to make use of the two-wheeler principle, is regarded as the forerunner of the bicycle. The dandy horse is a foot-propelled vehicle, powered by the rider's feet on the ground instead of the pedals of later bicycles.  It was invented by Karl Drais (who called it a <i>Laufmaschine</i> [<small>German: </small><span title=\"Representation in the International Phonetic Alphabet (IPA)\" lang=\"de-Latn-fonipa\">[\u02c8la\u028afma\u02cc\u0283i\u02d0n\u0259]</span>, \"running machine\"]) in 1817, and then patented by him in France in February 1818 using the term <i>v\u00e9locip\u00e8de</i>. It is also known as a <i>Draisine</i> (<small>German: </small><span title=\"Representation in the International Phonetic Alphabet (IPA)\" lang=\"de-Latn-fonipa\">[d\u0281a\u026a\u02c8zi\u02d0n\u0259]</span> <span>(<span><span><span></span>listen</span></span>)</span> in German, a term used in English only for light auxiliary railcars regardless of their form of propulsion), and as a <i>draisienne</i> (<small>French:\u00a0</small><span title=\"Representation in the International Phonetic Alphabet (IPA)\" lang=\"fr-Latn-fonipa\">[dr\u025bzj\u025bn]</span> in French and English. In English, it is also sometimes still known as a velocipede, but that term now also has a broader meaning.\n</p>\n\n\n`

Rendered and cleaned up:

> <p>The <b>dandy horse</b>, a derogatory term for what was first called a <b>Laufmaschine</b> (in German), then a <b>v&#x00e9;locip&#x00e8;de</b> or <b>draisienne</b> (in French and then English), and then a <b>pedestrian curricle</b> or <b>hobby-horse</b>, or <b>swiftwalker</b>, is a human-powered vehicle that, being the first means of transport to make use of the two-wheeler principle, is regarded as the forerunner of the bicycle. The dandy horse is a foot-propelled vehicle, powered by the rider's feet on the ground instead of the pedals of later bicycles.  It was invented by Karl Drais (who called it a <i>Laufmaschine</i> [<small>German: </small><span title="Representation in the International Phonetic Alphabet (IPA)" lang="de-Latn-fonipa">[&#x02c8;la&#x028a;fma&#x02cc;&#x0283;i&#x02d0;n&#x0259;]</span>, "running machine"]) in 1817, and then patented by him in France in February 1818 using the term <i>v&#x00e9;locip&#x00e8;de</i>. It is also known as a <i>Draisine</i> (<small>German: </small><span title="Representation in the International Phonetic Alphabet (IPA)" lang="de-Latn-fonipa">[d&#x0281;a&#x026a;&#x02c8;zi&#x02d0;n&#x0259;]</span> in German, a term used in English only for light auxiliary railcars regardless of their form of propulsion), and as a <i>draisienne</i> (<small>French:&#xa0;</small><span title="Representation in the International Phonetic Alphabet (IPA)" lang="fr-Latn-fonipa">[dr&#x025b;zj&#x025b;n]</span> in French and English. In English, it is also sometimes still known as a velocipede, but that term now also has a broader meaning.</p>

If this looks too verbose, the text could be collapsed beyond a given length (or even entirely), to be exposed only if the user selects to show it.

**Comment by hay** [comment]
Good suggestion! This is now added as a small on-demand button on all items that have a sitelink to the article in the users language, e.g. if Depictor is displayed in French you'll only get this button if there's a French WP article. 

For an example see https://hay.toolforge.org/depictor/?queryType=qid&queryValue=Q1125101

**Comment by waldyrious** [comment]
> This is now added as a small on-demand button

Awesome! I have a few observations, which I've numbered in case you want to respond to them separately:

1. By describing this as a "button", I spent several seconds looking confusedly at the interface until I realized that it's actually rendered as a plain link! :sweat_smile:
2. In fact, it does make sense to me that this should be a button, matching the style of the "Skip item" button, and perhaps placed alongside it:
   ![image](https://github.com/hay/wiki-tools/assets/478237/9c4aaa33-e021-4214-acad-06c85666604e)
3. (On a side note, the difference between the "Skip item" button and the "Skip" button above the image is not immediately clear. Maybe changing the first to "Skip all images for this item" or the second to "Skip this image" could help? These are mouthfuls, I know — I don't have a great suggestion here.)
4. The fetched description is not preserved when one moves from one image to the next (for the same item). While I understand that it should not be needed once one reads the description once, I don't see why it can't be kept since it's already fetched anyway. And in any case, one may need to re-read the description more carefully if a more challenging image comes after the one that was shown when one first fetches the description.
5. Perhaps the "Skip" (image) button could have a tooltip suggesting us to fetch the Wikipedia description, in case the reason for the ambiguity is the player's uncertainty about what the concept's exact definition is?
6. (Another side note: since the item box can contain an image, as is the case in the screenshot above, perhaps it would be a good idea to change "Is &lt;item&gt; clearly depicted in *this image*?" to "Is &lt;item&gt; clearly depicted in *the image below*"?

**Comment by hay** [comment]
Hey @waldyrious, thanks for all the constructive and extensive feedback. I've done an update and changed a couple of things:

1 & 2) This is changed now to be a button next to the 'skip item' button, as you suggested
3) Yeah, i think this is a bit of a mouthful indeed, especially on mobile where there's limited space.
4) This was definitely not intented behaviour, so good that you find the bug. This is fixed now.
5) Hmm... i wonder how many times the summary would help in that case, and i think it would be irritating to have the tooltip everytime you hover over that button.
6) Good point. I've changed this label. Note you can translate and change labels directly using the [ToolTranslate](https://tooltranslate.toolforge.org/#tool=59) tool. Translations might take a little while to update.

**Comment by waldyrious** [comment]
Thanks for considering and addressing my suggestions! Just a small note about this:

> i think it would be irritating to have the tooltip everytime you hover over that button.

AFAIK tooltips only appear, by default, after a small delay if the cursor pauses over the element. That happening is a good indicator that the person is unsure (otherwise they'd click right away). But it's not a big deal, and I won't insist if you prefer not having the tooltip :)
