### ISSUE TITLE
`hay.toolforge.org` is down

### ISSUE THREAD

**Issue by gy-mate** [hay/wiki-tools#144]
`hay.toolforge.org` (incl. `/depictor`) is unreachable. Tested with multiple devices and network connections.

![image](https://github.com/hay/wiki-tools/assets/13014176/640c5813-2b81-4740-955e-c9d8e50b2ae5)

![image](https://github.com/hay/wiki-tools/assets/13014176/2a70f9fe-94b0-4735-9115-82d70a01d157)

**Comment by hay** [comment]
Thanks for noticing. I'm getting
```
2024-04-02 15:14:07: server.c.973) [note] sockets enabled again
2024-04-02 15:14:07: server.c.980) [note] sockets disabled, connection limit reached
```

Investigating, maybe i'll just try restarting the webservice and see what happens.

**Comment by hay** [comment]
Okay, service is restarted, things seem to be operational again.

**Comment by gy-mate** [comment]
@hay Thank you! :)

**Comment by hay** [comment]
Welcome!
