### ISSUE TITLE
directory: Search field broken on mobile

### ISSUE THREAD

**Issue by Krinkle** [hay/wiki-tools#20]
When using https://tools.wmflabs.org/hay/directory/# in Mobile Safari it usually only recognises the first letter I type. After that, no matter how long I wait how try to blur/focus the field the value is ignored.

It says `Found 240 tools for "A". Reset?`.

Looks like maybe `ng-keyup` isn't mobile friendly?

**Comment by hay** [comment]
Could you take a look at it again? I've completely removed Angular and i'm using jQuery instead now. Maybe it's an easy fix to make it mobile friendly.
