### ISSUE TITLE
directory: Author filter message is stale

### ISSUE THREAD

**Issue by Krinkle** [hay/wiki-tools#21]
1. https://tools.wmflabs.org/hay/directory/
2. type "timo"
3. In the 4 results, click on "Timo Tijhof" in one of them.
4. Click "Reset" in the "Found 4 tools for timo. Reset?" message.

Expected:

See all tools by this author but without the keyword filter, or (also understandable) go back to see all tools.

Actual:

It does a little bit of both. The list goes back to see all results, however the "Only showing tools with X as author." message stays. It even gets updated to say "240 tools" in "Only showing 240 tools with Timo Tijhof as author." – which is wrong, I don't have that many tools! :grinning:

**Comment by hay** [comment]
I completely rewrote the Directory from Angular to plain old PHP + jQuery and this bug seems to be fixed without any effort. Hurrah!
