### ISSUE TITLE
Tools not indexed, please re-enable your cron job

### ISSUE THREAD

**Issue by Rillke** [hay/wiki-tools#22]
- [Listed my tools yesterday](https://wikitech.wikimedia.org/w/index.php?title=User%3AHay%2Fdirectory&type=revision&diff=169157&oldid=168540)
- [crawler.log: 404 - Not Found](https://tools.wmflabs.org/hay/directory/crawler.log)
- Still not added to https://tools.wmflabs.org/hay/directory

**Comment by Rillke** [comment]
- https://lists.wikimedia.org/pipermail/labs-l/2015-June/003831.html
- https://lists.wikimedia.org/pipermail/labs-l/2015-June/003867.html

**Comment by hay** [comment]
Thanks. This has been fixed.

**Comment by Rillke** [comment]
:+1:
