### ISSUE TITLE
Outdated crawl logs for directory

### ISSUE THREAD

**Issue by cdrini** [hay/wiki-tools#24]
The crawl logs at https://tools.wmflabs.org/hay/directory/crawler.log seem to be very outdated. The last update was in 2014 (2014-08-13T14:49:25+02:00). Is the crawler not running, or are the logs not being written to?

**Comment by Fannon** [comment]
I've just added two of my own tools and realized this, too.

Is the crawler still working?

**Comment by hay** [comment]
I've run the script manually, at least it updated again.
Open this ticket again if things don't work. Thanks.
