### ISSUE TITLE
by author, with spaces, not working

### ISSUE THREAD

**Issue by quiddity-wp** [hay/wiki-tools#25]
(First: Love the directory!)

I noticed that the listings by author don't work currently, if the name has spaces. [Screenshot](http://i.imgur.com/UAuBC2U.png)
E.g. These don't work
* https://tools.wmflabs.org/hay/directory/#/author/Magnus%20Manske
* https://tools.wmflabs.org/hay/directory/#/author/S%C3%A9bastien%20Santoro%20aka%20Dereckson

but this does:
* https://tools.wmflabs.org/hay/directory/#/author/Mormegil

**Comment by hay** [comment]
This seems to be fixed now.

**Comment by bd808** [comment]
Maybe it depends on the user-agent that you are using? I'm getting "Only showing 0 tools with Timo%20Tijhof as author." when using Firefox 43 (note the %20 in the output). If I use Chrome 47 then I get "Only showing 4 tools with Timo Tijhof as author." (space is not URL encoded).

Using the developer tools in both browsers shows the difference. In Firefox, `window.location.hash` === "#/author/Timo%20Tijhof". In Chrome, `window.location.hash` === "#/author/Timo Tijhof".

**Comment by quiddity-wp** [comment]
@hay Hi :-) 
I think this needs to be reopened? 
Per bd808's comment, I get different results in Firefox vs Chrome, from clicking through via authorname, for multi-word authornames, at https://tools.wmflabs.org/hay/directory/

Also, directly accessing an encoded URL (e.g. copied or clicked from a mail client) with Chrome will not work, e.g. (with markdown formatting)
* [https://tools.wmflabs.org/hay/directory/#/author/Magnus%20Manske](https://tools.wmflabs.org/hay/directory/#/author/Magnus%20Manske)
* [https://tools.wmflabs.org/hay/directory/#/author/Magnus Manske](https://tools.wmflabs.org/hay/directory/#/author/Magnus Manske)
