### ISSUE TITLE
Add "License" to toolinfo.json

### ISSUE THREAD

**Issue by bd808** [hay/wiki-tools#26]
I think it would be a nice feature to add support for an optional "license" field in the toolinfo.json spec. The [Composer json schema](https://getcomposer.org/doc/04-schema.md#license) allows an array of identifiers from https://spdx.org/licenses/ which seems pretty reasonable.

**Comment by bd808** [comment]
If you are willing to provide me a few pointers to all the things that would need to be changed I would try to make a patch to add this support.

**Comment by ricordisamoa** [comment]
Considering the variety of licenses each tool may be released under, the unlikeliness of such information being useful to the general public, and the popularity of general-purpose schemas such as composer.json and package.json, I oppose.

**Comment by hay** [comment]
This seems like a useful addition. I think this might be displayed on the website aside from the 'source available' line, something like "(source available under a MIT license)". 

I wouldn't be in favour of allowing an array of licenses though. SPDX has something called 'composite license expressions' which seem to allow multiple licenses in a string format.
