### ISSUE TITLE
Duplicate projects

### ISSUE THREAD

**Issue by dmm42** [hay/wiki-tools#3]
I've changed my toolinfo.json to add the repository and now the same project appears two times.

* https://tools.wmflabs.org/hay/directory/#/search/lists%20pro
* https://tools.wmflabs.org/hay/directory/#/search/maint

**Comment by hay** [comment]
@dmm42, @ricordisamoa: could you provide a link to your toolinfo.json? I think you have the same tool twice in two toolinfo.json files. Your names are different as well.

**Comment by dmm42** [comment]
* http://tools.wmflabs.org/lists/toolinfo.json
* http://tools.wmflabs.org/maintgraph/toolinfo.json

**Comment by hay** [comment]
There's another toolinfo.json that has 'MaintGraph' (instead of 'labs-tools-maintgraph') as a name, that's why you're having a duplicate. You might want to find out who's also adding your tool to the directory :)

**Comment by dmm42** [comment]
Thanks. Do you know the url of the second toolinfo.json?

**Comment by hay** [comment]
No, sorry. It's somewhere in the list of all the URL's, but there's no easy way to check which one has your tool :/

**Comment by dmm42** [comment]
I have checked the content of all the URLs with grep and there are no duplicates of these tools.
