### ISSUE TITLE
Directories not loading

### ISSUE THREAD

**Issue by quiddity-wp** [hay/wiki-tools#33]
At https://tools.wmflabs.org/hay/directory/
and https://tools.wmflabs.org/hay/wdd/

I'm only seeing the page title, and top header. No errors in webconsole.
![selection_001](https://cloud.githubusercontent.com/assets/6633202/20497697/024c1b4c-afdf-11e6-8248-1ddb7791d285.png)

**Comment by Abbe98** [comment]
Same here.

**Comment by hay** [comment]
Apparently, something was wrong with permissions on the tool server. I don't know what, but i think i fixed it.

**Comment by Abbe98** [comment]
Amazing thanks @hay !
