### ISSUE TITLE
Add tools listed in Wikidata

### ISSUE THREAD

**Issue by nichtich** [hay/wiki-tools#49]
Tools could also be described in Wikidata, e.g. instances of [Wikidata tool](https://www.wikidata.org/wiki/Q20726407). Wikidata allows to describe tools by anyone. This is important because creation and updating `toolinfo.json` is a bootleneck in this directory. In Wikidata we can also add additional connections, e.g. dependencies between tools, date of creation etc.

Detection of duplicates (same tool described in Wikidata and listed in https://wikitech.wikimedia.org/wiki/User:Hay/directory) could be on the `url` key and the [official website](https://www.wikidata.org/wiki/Property:P856).

**Comment by hay** [comment]
In my opinion, using the `toolinfo.json` file to describe a tool is a feature, not a bottleneck, and there are many reasons why i don't think Wikidata would be the best place for editing the tool information. A larger write-up on this subject is available in [this comment](https://phabricator.wikimedia.org/T115650#3030000) on Phabricator.
