### ISSUE TITLE
Allow some flexibility while searching in the Tools directory

### ISSUE THREAD

**Issue by sivaraam** [hay/wiki-tools#51]
The most simple case of searching is doing exact matching of the search terms and the search strings. To this end the search Hay's tools directory seems to be ironical. Searching for "pet" shows "PetScan" as one of the results among others. Surprisingly, when I search for "Pet" I get absolutely **no results**.

**Search query "pet"**
![hays_tools_search_issue](https://user-images.githubusercontent.com/12448084/38893305-8f890f2c-42a7-11e8-87af-51be62ad936a.png)

**Search query "Pet"**
![hays_tools_search_issue_1](https://user-images.githubusercontent.com/12448084/38893324-9bd029b4-42a7-11e8-8a7f-081547c17d4b.png)

*Note*: Not that I'm criticizing but I'm surprised by this particular issue. Of course, I do find Hay's tools directory to be really helpful. Thanks a lot for the work, BTW.

**Comment by hay** [comment]
Hey, this was an issue because search queries were not lowercased by default, while the text it uses to search through was. This is now fixed.
