### ISSUE TITLE
Mention that adding tool via Toolsadmin is possible in instructions as well

### ISSUE THREAD

**Issue by urbanecm** [hay/wiki-tools#52]
It would be cool if the possibility about adding a tool via Toolsadmin can be in the instructions as well https://tools.wmflabs.org/hay/directory/#addtool. 

Thank you for your work, Hay!

**Comment by nichtich** [comment]
Could you describe what you mean by "adding a tool via Toolsadmin"?

**Comment by hay** [comment]
Good point, this is now added. Thanks for reporting!
