### ISSUE TITLE
Add "unselect all" to propbrowse's datatype selector

### ISSUE THREAD

**Issue by nyurik** [hay/wiki-tools#56]
The list of datatypes in the prop browser is very long, so when i want to see just a single datatype, it takes some time to uncheck them all except the one I need. Ideally, there should be "select only this" link, that would unselect all others (this can be shown only on mouse hover, e.g. how Kayak does it). A simpler second best would be to have a "uncheck all".  Thanks!

![image](https://user-images.githubusercontent.com/1641515/63826427-e63cd080-c92c-11e9-94dc-e4a3593a11db.png)

**Comment by hay** [comment]
Yes, that feels like a simple yet effective addition. If you have the time, feel free to send me a PR.

**Comment by hay** [comment]
Well, this turned out so simple that i just added it. There are now 'select all' and 'deselect all types' buttons.

**Comment by hay** [comment]
Good point. This is fixed now.
