### ISSUE TITLE
missing npm package wikidata-ux

### ISSUE THREAD

**Issue by waldenn** [hay/wiki-tools#67]
Hi Hay,

I tried to use the sdsearch tool, but the [wikidata-ux](https://github.com/hay/wiki-tools/blob/master/public_html/sdsearch/js/commons-api.js#L1) is not being found when building it, and I could not find this package on npm. Could you fix this? Thanks!

This tool looks like a really good start at making structured querying a bit easier for all (which is not an easy problem). I've tried using you vizquery tool for my own [project](https://conze.pt), but it has a few issues (like reloading the query form upon each field input). I think this UI already feels much more fluid and natural. Looking forward to see where this goes. Thanks again.

**Comment by hay** [comment]
Hey @waldenn,
thanks for reporting this. I've folded all the code from the (indeed not-existing yet) `wikidata-ux` package into this repo with the last commit, so a `git pull` should fix it. Let me know when you've built something on the basis of this project!

**Comment by waldenn** [comment]
Thanks Hay. Will let you know.
