### ISSUE TITLE
Duplicate challenge in Depictor

### ISSUE THREAD

**Issue by trnstlntk** [hay/wiki-tools#75]
Yesterday, I have created [a new challenge in Depictor (Public art)](https://hay.toolforge.org/depictor/?challenge=37). And it seems to have generated [a duplicate](https://hay.toolforge.org/depictor/?challenge=38)...

![image](https://user-images.githubusercontent.com/9881645/153704168-0a38cbbd-9a19-4113-8540-74741a8e1e52.png)

**Comment by hay** [comment]
Thanks for reporting. The challenge is archived, so it will no longer show up.
