### ISSUE TITLE
Wikimedia Documentation Directory has no results

### ISSUE THREAD

**Issue by samwilson** [hay/wiki-tools#85]
No search term works, nor does 'show all'. The intro says "Search through 0 tools here."

https://hay.toolforge.org/wdd/#/showall

**Comment by hay** [comment]
Hey Sam, the WDD has been deprecated for a pretty long time. It's indicated on the Tool overview page, but i probably should put up a notice on the page as well.

**Comment by samwilson** [comment]
Oh, no worries. Thanks.

I found it via Toolhub, but it looks like you've removed it from there now. :)
