### ISSUE TITLE
Preload images in Depictor

### ISSUE THREAD

**Issue by thibaultmol** [hay/wiki-tools#93]
I've started using the tool today and noticed that I'm often just waiting for the images (or the next item, If I had to skip an entire item) to load. I feel like if (maybe using a service worker) it could fetch the next item and it's images in the background I would spend less time waiting and more time contributing.

(Great tool though btw, very cool!)

**Comment by hay** [comment]
This was a bit more complicated than i thought, because the next 'candidates' were previously loaded randomly (maybe to avoid race conditions). So i changed that and now the first 50 candidate images for every item are preloaded, and beyond that at least the next image is preloaded.
